### ISSUE TITLE
I tested it and retweeted tweets don't alert. How do I monitor multiple users?

### ISSUE THREAD

**Issue by szsyzx** [xdsai/twitter-monitor#2]
I tested it and retweeted tweets don't alert. How do I monitor multiple users?

**Comment by xdsai** [comment]
Because retweets don't show up in the endpoint we're using, only tweets do. If you want retweets to show up, look in the docs for a different endpoint that offers that, and rebuild the code around it. To monitor multiple users, you either have to use asynchronous requests and split the API key between multiple threads, making the response of the monitor slower, or just add additional API keys and use those in separate instances of the program.
